// Generated by https://quicktype.io

class CastMovie {
  String? knownForDepartment;
  String? originalName;
  String? profilePath;
  String? character;


  CastMovie({
    this.knownForDepartment,
    this.originalName,
    this.profilePath,
    this.character,

  });
  factory CastMovie.fromMap(Map<String,dynamic> cast){
    return CastMovie(
      knownForDepartment: cast['known_for_department'],
      originalName: cast['original_name'],
      profilePath: cast['profile_path'],
      character: cast['character']

      
    );
  }
}
